### ISSUE TITLE
ToDo Liste für Wood Stone Age

### ISSUE THREAD

**Issue by BakermanLP** [BakermanLP/ProjectRET-AoT#1]
**Generelle ToDos**
- [ ] Resourcepack Auswahl

**Biome einsetzen**
- [x] Tinkers Construct Slime Islands
- [x] Wolliwood

**Konfiguration Anpassungen**
- [ ] Custom Main Menu andere Auflösungen testen und anpassen

**Abschliessende Configs**
- [ ] DefaultOptions setzen
- [ ] World Stripper entfernen
- [ ] First Kit einstellen

**Server Einstellungen**
- [ ] WorldBorder
- [ ] World PreGeneration
- [ ] Permissions einrichten

**Comment by BakermanLP** [comment]
Configuration Anpassungen in
Forestry engine
Extra utilities engines

**Comment by BakermanLP** [comment]
Kleines Update der Punkte:
**World Stripper entfernen**
- Dient zum Testen der Ore Generation

**First Kit**
-  ist gewandert von Server Einstellung zu Client Einstellung

**Grapplemod**
- ist nun eingeschränkt mittels eines CraftTweaker Scriptes
