### ISSUE TITLE
ToDo Liste vor Release

### ISSUE THREAD

**Issue by BakermanLP** [BakermanLP/ProjectRET-AoT#185]
Modpack 
- [x] backpacks 1.11.2 - 3.4.2.jar entfernen
- [x] WearableBackpacks-1.11.2-2.5.0.jar entfernen
- [x] tellme-1.11.2-0.5.4.jar entfernen
- [x] World-Stripper-1.4.1-1.11.0.jar entfernen
- [x] Dev Server aus server.dat entfernen
- [x] letzte Änderungen Questbook einpflegen
- [x] Nochmal Testen Resourcepack Installation
- [x] Nochmal Testen Tastaturbelegung Konfiguration
- [ ] Eventuell Update von ModpackUtil
- [ ] Startinventar testen (Welche vorhandene Mod/Plugin)

Server
- [x] Server West aufsetzen und einrichten
- [x] North, South, West und Mining auf Default setzen
- [x] RedProtect Einträge löschen auf allen Servern
- [x] Datenbank leeren
- [ ] Portale in Lobby reaktivieren
- [x] Portale in North, South und West zurück zur Lobby
- [x] Portale in North, South und West zur Mining Welt (Spart Umweg über Lobby)
- [ ] Lobby World Border knapp um Berg ziehen
- [x] Standort für Stadt auf North und South 
- [ ] Auf North, South und West eventuell Zugang zum zentralen Berg verbieten (RedProtect admin flag enter??)
- [ ] Portal in Lobby für West ?!?!?! 
- [ ] Voranmeldungen in Whitelist eintragen

**Comment by hellamie** [comment]
Zugang zum Berg würde ich machen.

Portal nach West?..dan kann jeder zu euch kommen und spionieren..wenn ihr das wollt ja..soll es Video onlie bleiben..nein

**Comment by JuliusFreudenberger** [comment]
Ist mit Tastaturbelegung die Standard Keybind gemeint?
Soll ich da nochmal schauen, dass diese die wichtigen Tasten sinnvoll (und vor allem nicht doppelt) belegt?

**Comment by BakermanLP** [comment]
Mir geht es in erster Linie bei der Tastaturbelegung um das autmatische Einstellen der Tastaturbelegung beim ersten Start des Clients. Du kannst gerne mal schauen.

**Comment by DerOliDE** [comment]
Die OP Listen der jeweiligen Server muss auch noch resetet werden.

**Comment by BakermanLP** [comment]
Bitte mir die geänderten Dateien sagen, sonst überschreibe ich die mit
eventuellen Updates

Oliver <notifications@github.com> schrieb am Do., 30. Nov. 2017, 17:41:

**Comment by DerOliDE** [comment]
Die config zu permissionmanager liegt in ./config/permissionmanager/*

**Comment by hellamie** [comment]
Portale an sich sind gebaut..müssen nur noch fertig verschönert (verstreetet) werden und aktiviert.  Außer west..das kommt am Samstag

**Comment by BakermanLP** [comment]
In der redprotect config muss der level-name aus den server.properties als allowed worlds drin stehen sonst funktioniert es überhaupt nicht wenn man kein op is

**Comment by DerOliDE** [comment]
Beispiel vom mining server ./config/RedProtect/config.conf 
```
allowed-claim-worlds=[
    Flatlands,
    world,
    DIM-1,
    DIM1
]
```
Wobei world eigentlich raus könnte, da wir diese Welt nicht haben.

**Comment by JuliusFreudenberger** [comment]
Bezüglich der Tastaturbelegung:
- Ich habe den Keyboard-Wizard passenderweise auf 'K' gelegt, um 'F1' aus der Doppelbelegung zu bekommen.
- Die Liquid View habe ich auf 'J' umgelegt, um die Quest Log erreichbar zu machen.
Die anderen Doppelbelegungen 'L Shift' und 'R' machen keine Probleme.

**Comment by DerOliDE** [comment]
Ich räume den Issue auch mal auf, das Pack wurde ja schon released. :)
